test_that("CI keeps platform and release coverage while skipping documentation-only work", {
  env <- new.env(parent = baseenv())
  sys.source(file.path(project_root, "tools", "ci_plan.R"), envir = env)
  docs <- env$ci_plan(c("README.md", "docs/usage.md"), "push", "0.6.1")
  expect_false(docs$code)
  expect_false(docs$release)
  runtime <- env$ci_plan("R/calibration.R", "push", "0.6.1")
  expect_true(runtime$code)
  expect_match(runtime$matrix, '"r":"4.3"', fixed = TRUE)
  expect_match(runtime$matrix, '"paml":"true"', fixed = TRUE)
  expect_match(runtime$matrix, "macos-latest", fixed = TRUE)
  expect_match(runtime$matrix, "windows-latest", fixed = TRUE)
  release <- env$ci_plan("R/version.R", "push", "0.6.0")
  expect_true(release$release)
  expect_true(release$code)
  expect_false(env$ci_plan("R/version.R", "pull_request", "0.6.0")$release)
  expect_true(env$ci_plan(character(), "schedule", "0.6.1")$code)
  expect_true(env$ci_plan(character(), "workflow_dispatch", "0.6.1")$code)
})

test_that("quoted species labels preserve numeric IDs without temporary-prefix collisions", {
  tree <- read.tree(text = "(('001':1,B_sp:1)'002':1,C_sp:2)PLACEHOLDER123;")
  tree <- validate_species_tree_labels(tree)
  expect_identical(tree$tip.label[[1]], "001")
  expect_identical(tree$node.label, c("PLACEHOLDER123", "002"))
  expect_error(validate_gene_tree_labels(read.tree(text = "(A:1,B:1);")), "non-labeled")
})
