#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
check_only <- identical(args, "--check")
if (length(args) > 1L || (length(args) == 1L && !check_only)) {
    stop("Usage: Rscript tools/build_radte.R [--check]")
}

source("R/load.R", local = TRUE)

render_radte <- function() {
    rendered <- c(
        "#!/usr/bin/env Rscript",
        "",
        "# Generated by tools/build_radte.R from the canonical modules under R/.",
        "# Do not edit this bundled distribution script directly.",
        ""
    )
    for (module_file in radte_module_files) {
        rendered <- c(
            rendered,
            paste0("# ---- BEGIN ", module_file, " ----"),
            readLines(module_file, warn = FALSE),
            paste0("# ---- END ", module_file, " ----"),
            ""
        )
    }
    c(rendered, "radte_main()")
}

rendered <- render_radte()
if (check_only) {
    current <- if (file.exists("radte.r")) readLines("radte.r", warn = FALSE) else character()
    if (!identical(current, rendered)) {
        stop("radte.r is stale. Run: Rscript tools/build_radte.R")
    }
    cat("radte.r is up to date.\n")
} else {
    output_tmp <- tempfile(pattern = ".radte-build-", tmpdir = ".")
    on.exit(unlink(output_tmp), add = TRUE)
    writeLines(rendered, output_tmp, useBytes = TRUE)
    backup_file <- NULL
    if (file.exists("radte.r")) {
        backup_file <- tempfile(pattern = ".radte-backup-", tmpdir = ".")
        if (!file.rename("radte.r", backup_file)) {
            stop("Failed to stage the existing radte.r for replacement.")
        }
    }
    if (!file.rename(output_tmp, "radte.r")) {
        if (!is.null(backup_file) && file.exists(backup_file)) {
            file.rename(backup_file, "radte.r")
        }
        stop("Failed to replace radte.r with the generated bundle.")
    }
    if (!is.null(backup_file)) unlink(backup_file)
    Sys.chmod("radte.r", mode = "0755")
    cat("Generated radte.r from R/ modules.\n")
}
