name: Tag from radte.r

on:
  workflow_dispatch:  # 手動実行
  push:
    branches: [main]  # main更新時でも可

jobs:
  extract-version-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from radte.r
        id: extract_version
        run: |
          version=$(grep "^radte_version" radte.r | sed -E "s/.*'([0-9.]+)'.*/\1/")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check latest tag
        id: check_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag | sort -V | tail -n 1)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Create new tag if needed
        if: steps.extract_version.outputs.version != steps.check_tag.outputs.latest_tag
        run: |
          version=${{ steps.extract_version.outputs.version }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v$version"
          git push origin "v$version"
